export const SITE = {
  website: "https://brandonvisca.com/",
  author: "Brandon Visca",
  profile: "https://github.com/visbran",
  desc: "Blog tech francophone : homelab, auto-hébergement, Linux, macOS et indépendance numérique. Des guides concrets pour reprendre le contrôle de tes données.",
  title: "Brandon Visca",
  ogImage: "og.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showGalleries: false,
  showGalleriesInIndex: false,
  showBackButton: true,
  heroTerminalPrompt: {
    prefix: "~/homelab",
    branch: "main",
    suffix: "$",
  },
  backdropEffects: {
    cursorGlow: false,
    grain: true,
  },
  editPost: {
    enabled: false,
    text: "Suggérer une correction",
    url: "https://github.com/visbran/brandonvisca.com/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "fr",
  timezone: "Europe/Paris",
  introAudio: {
    enabled: true,
    src: "https://fluxfm.streamabc.net/flx-chillhop-mp3-128-8581707",
    isStream: true,
    label: "LOFI",
    duration: 30,
  },
} as const;
